spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=saas_user
    username: postgres
    password: Sherlock!gmt!2022
    driver-class-name: org.postgresql.Driver
