logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=saas_user
    username: postgres
    password: Sherlock!gmt!2022
    driver-class-name: org.postgresql.Driver
